locals {
  # GCP resource names must be lowercase; var.github_repo ("lexicon-MovieAPI")
  # is only used for the WIF binding below, where casing has to match GitHub
  # exactly.
  app_name = "movieapi"

  apis = [
    "run.googleapis.com",
    "artifactregistry.googleapis.com",
    "iamcredentials.googleapis.com",
    "secretmanager.googleapis.com",
    "sts.googleapis.com",
  ]

  envs = ["staging", "prod"]

  deployer_roles = [
    "roles/run.admin",
    "roles/artifactregistry.writer",
    "roles/iam.serviceAccountUser",
    "roles/secretmanager.secretAccessor",
  ]

  # roles/logging.logWriter backs Logging:Sink=GoogleCloudLogging (see
  # Program.cs) - the runtime identity calls the Cloud Logging API directly
  # via Application Default Credentials, so it needs this beyond the secret
  # access every app in this project needs.
  runtime_roles = [
    "roles/secretmanager.secretAccessor",
    "roles/logging.logWriter",
  ]
}

# --- Owned by the shared bootstrap stack ------------------------------------
#
# The WIF pool/provider and the "apps" Artifact Registry repo are managed in
# a separate Terraform stack (various-terraform/gcp-bootstrap), not here.
# They're referenced read-only via data sources rather than declared as
# resources, since re-declaring them here would try to create already-
# existing, uniquely-named GCP objects and fail with 409s.

data "google_iam_workload_identity_pool" "github_actions" {
  workload_identity_pool_id = "github-actions"
}

data "google_iam_workload_identity_pool_provider" "github" {
  workload_identity_pool_id          = data.google_iam_workload_identity_pool.github_actions.workload_identity_pool_id
  workload_identity_pool_provider_id = "github"
}

data "google_artifact_registry_repository" "apps" {
  location      = var.region
  repository_id = "apps"
}

# API enablement is idempotent (enabling an already-enabled API just
# succeeds), so it's safe for this stack to also declare it rather than
# assume the bootstrap stack's state will always be the one managing it.
resource "google_project_service" "this" {
  for_each           = toset(local.apis)
  project            = var.project_id
  service            = each.value
  disable_on_destroy = false
}

# --- This app's own resources ------------------------------------------------

# Used by GitHub Actions to build/push/deploy.
resource "google_service_account" "deployer" {
  account_id   = "${local.app_name}-deployer"
  display_name = "${local.app_name} GitHub Actions deployer"
}

# Used as the running Cloud Run services' own identity (frontend + backend
# share one runtime identity, same as the roles they need are identical).
resource "google_service_account" "runtime" {
  account_id   = "${local.app_name}-run"
  display_name = "${local.app_name} Cloud Run runtime identity"
}

resource "google_project_iam_member" "deployer" {
  for_each = toset(local.deployer_roles)
  project  = var.project_id
  role     = each.value
  member   = "serviceAccount:${google_service_account.deployer.email}"
}

resource "google_project_iam_member" "runtime" {
  for_each = toset(local.runtime_roles)
  project  = var.project_id
  role     = each.value
  member   = "serviceAccount:${google_service_account.runtime.email}"
}

# Let GitHub Actions, but only from this repo, impersonate the deployer SA -
# no downloaded JSON keys.
resource "google_service_account_iam_member" "deployer_wif_binding" {
  service_account_id = google_service_account.deployer.name
  role               = "roles/iam.workloadIdentityUser"
  member             = "principalSet://iam.googleapis.com/${data.google_iam_workload_identity_pool.github_actions.name}/attribute.repository/${var.github_org}/${var.github_repo}"
}

# Secret containers only - the actual values (DB connection string, OpenIddict
# signing/encryption keys, admin password) are pushed in separately so they
# never land in this stack's state. DB connection string comes from the Neon
# stack's output; the OpenIddict keys and admin password are generated by
# hand (see outputs below for the exact commands).
resource "google_secret_manager_secret" "db_url" {
  for_each  = toset(local.envs)
  secret_id = "${local.app_name}-${each.value}-database-url"

  replication {
    auto {}
  }

  depends_on = [google_project_service.this]
}

resource "google_secret_manager_secret" "openiddict_signing_key" {
  for_each  = toset(local.envs)
  secret_id = "${local.app_name}-${each.value}-openiddict-signing-key"

  replication {
    auto {}
  }

  depends_on = [google_project_service.this]
}

resource "google_secret_manager_secret" "openiddict_encryption_key" {
  for_each  = toset(local.envs)
  secret_id = "${local.app_name}-${each.value}-openiddict-encryption-key"

  replication {
    auto {}
  }

  depends_on = [google_project_service.this]
}

# Backs Seed:AdminPassword (see AdminUserSeeder) - without this, staging/prod
# never seed an admin account since that seeder is deliberately a no-op when
# unconfigured. Seed:AdminEmail isn't sensitive enough to warrant its own
# per-env secret; it's passed as a plain env var from the ADMIN_EMAIL GitHub
# secret instead (see deploy-staging.yml/deploy-prod.yml).
resource "google_secret_manager_secret" "admin_password" {
  for_each  = toset(local.envs)
  secret_id = "${local.app_name}-${each.value}-admin-password"

  replication {
    auto {}
  }

  depends_on = [google_project_service.this]
}
